// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: meta.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EstablishReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=Addr,proto3" json:"Addr,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=Type,proto3" json:"Type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EstablishReq) Reset() {
	*x = EstablishReq{}
	mi := &file_meta_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EstablishReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstablishReq) ProtoMessage() {}

func (x *EstablishReq) ProtoReflect() protoreflect.Message {
	mi := &file_meta_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstablishReq.ProtoReflect.Descriptor instead.
func (*EstablishReq) Descriptor() ([]byte, []int) {
	return file_meta_proto_rawDescGZIP(), []int{0}
}

func (x *EstablishReq) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *EstablishReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type EstablishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"`
	Err           string                 `protobuf:"bytes,2,opt,name=Err,proto3" json:"Err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EstablishResponse) Reset() {
	*x = EstablishResponse{}
	mi := &file_meta_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EstablishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstablishResponse) ProtoMessage() {}

func (x *EstablishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meta_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstablishResponse.ProtoReflect.Descriptor instead.
func (*EstablishResponse) Descriptor() ([]byte, []int) {
	return file_meta_proto_rawDescGZIP(), []int{1}
}

func (x *EstablishResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EstablishResponse) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type ShakeHandReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShakeHandReq) Reset() {
	*x = ShakeHandReq{}
	mi := &file_meta_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShakeHandReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShakeHandReq) ProtoMessage() {}

func (x *ShakeHandReq) ProtoReflect() protoreflect.Message {
	mi := &file_meta_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShakeHandReq.ProtoReflect.Descriptor instead.
func (*ShakeHandReq) Descriptor() ([]byte, []int) {
	return file_meta_proto_rawDescGZIP(), []int{2}
}

type ShakeHandResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShakeHandResp) Reset() {
	*x = ShakeHandResp{}
	mi := &file_meta_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShakeHandResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShakeHandResp) ProtoMessage() {}

func (x *ShakeHandResp) ProtoReflect() protoreflect.Message {
	mi := &file_meta_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShakeHandResp.ProtoReflect.Descriptor instead.
func (*ShakeHandResp) Descriptor() ([]byte, []int) {
	return file_meta_proto_rawDescGZIP(), []int{3}
}

var File_meta_proto protoreflect.FileDescriptor

const file_meta_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"meta.proto\x12\x05proto\"6\n" +
	"\fEstablishReq\x12\x12\n" +
	"\x04Addr\x18\x01 \x01(\tR\x04Addr\x12\x12\n" +
	"\x04Type\x18\x02 \x01(\tR\x04Type\"9\n" +
	"\x11EstablishResponse\x12\x12\n" +
	"\x04Type\x18\x01 \x01(\tR\x04Type\x12\x10\n" +
	"\x03Err\x18\x02 \x01(\tR\x03Err\"\x0e\n" +
	"\fShakeHandReq\"\x0f\n" +
	"\rShakeHandResp2\x82\x01\n" +
	"\bMaintain\x12<\n" +
	"\tEstablish\x12\x13.proto.EstablishReq\x1a\x18.proto.EstablishResponse\"\x00\x128\n" +
	"\tShakeHand\x12\x13.proto.ShakeHandReq\x1a\x14.proto.ShakeHandResp\"\x00B\tZ\a./protob\x06proto3"

var (
	file_meta_proto_rawDescOnce sync.Once
	file_meta_proto_rawDescData []byte
)

func file_meta_proto_rawDescGZIP() []byte {
	file_meta_proto_rawDescOnce.Do(func() {
		file_meta_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_meta_proto_rawDesc), len(file_meta_proto_rawDesc)))
	})
	return file_meta_proto_rawDescData
}

var file_meta_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_meta_proto_goTypes = []any{
	(*EstablishReq)(nil),      // 0: proto.EstablishReq
	(*EstablishResponse)(nil), // 1: proto.EstablishResponse
	(*ShakeHandReq)(nil),      // 2: proto.ShakeHandReq
	(*ShakeHandResp)(nil),     // 3: proto.ShakeHandResp
}
var file_meta_proto_depIdxs = []int32{
	0, // 0: proto.Maintain.Establish:input_type -> proto.EstablishReq
	2, // 1: proto.Maintain.ShakeHand:input_type -> proto.ShakeHandReq
	1, // 2: proto.Maintain.Establish:output_type -> proto.EstablishResponse
	3, // 3: proto.Maintain.ShakeHand:output_type -> proto.ShakeHandResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_meta_proto_init() }
func file_meta_proto_init() {
	if File_meta_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_meta_proto_rawDesc), len(file_meta_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_meta_proto_goTypes,
		DependencyIndexes: file_meta_proto_depIdxs,
		MessageInfos:      file_meta_proto_msgTypes,
	}.Build()
	File_meta_proto = out.File
	file_meta_proto_goTypes = nil
	file_meta_proto_depIdxs = nil
}
