// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.1
// source: meta.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Maintain_Establish_FullMethodName = "/proto.Maintain/Establish"
	Maintain_ShakeHand_FullMethodName = "/proto.Maintain/ShakeHand"
)

// MaintainClient is the client API for Maintain service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MaintainClient interface {
	Establish(ctx context.Context, in *EstablishReq, opts ...grpc.CallOption) (*EstablishResponse, error)
	ShakeHand(ctx context.Context, in *ShakeHandReq, opts ...grpc.CallOption) (*ShakeHandResp, error)
}

type maintainClient struct {
	cc grpc.ClientConnInterface
}

func NewMaintainClient(cc grpc.ClientConnInterface) MaintainClient {
	return &maintainClient{cc}
}

func (c *maintainClient) Establish(ctx context.Context, in *EstablishReq, opts ...grpc.CallOption) (*EstablishResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EstablishResponse)
	err := c.cc.Invoke(ctx, Maintain_Establish_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *maintainClient) ShakeHand(ctx context.Context, in *ShakeHandReq, opts ...grpc.CallOption) (*ShakeHandResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShakeHandResp)
	err := c.cc.Invoke(ctx, Maintain_ShakeHand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MaintainServer is the server API for Maintain service.
// All implementations must embed UnimplementedMaintainServer
// for forward compatibility.
type MaintainServer interface {
	Establish(context.Context, *EstablishReq) (*EstablishResponse, error)
	ShakeHand(context.Context, *ShakeHandReq) (*ShakeHandResp, error)
	mustEmbedUnimplementedMaintainServer()
}

// UnimplementedMaintainServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMaintainServer struct{}

func (UnimplementedMaintainServer) Establish(context.Context, *EstablishReq) (*EstablishResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Establish not implemented")
}
func (UnimplementedMaintainServer) ShakeHand(context.Context, *ShakeHandReq) (*ShakeHandResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShakeHand not implemented")
}
func (UnimplementedMaintainServer) mustEmbedUnimplementedMaintainServer() {}
func (UnimplementedMaintainServer) testEmbeddedByValue()                  {}

// UnsafeMaintainServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MaintainServer will
// result in compilation errors.
type UnsafeMaintainServer interface {
	mustEmbedUnimplementedMaintainServer()
}

func RegisterMaintainServer(s grpc.ServiceRegistrar, srv MaintainServer) {
	// If the following call pancis, it indicates UnimplementedMaintainServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Maintain_ServiceDesc, srv)
}

func _Maintain_Establish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EstablishReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaintainServer).Establish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Maintain_Establish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaintainServer).Establish(ctx, req.(*EstablishReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Maintain_ShakeHand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShakeHandReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaintainServer).ShakeHand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Maintain_ShakeHand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaintainServer).ShakeHand(ctx, req.(*ShakeHandReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Maintain_ServiceDesc is the grpc.ServiceDesc for Maintain service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Maintain_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Maintain",
	HandlerType: (*MaintainServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Establish",
			Handler:    _Maintain_Establish_Handler,
		},
		{
			MethodName: "ShakeHand",
			Handler:    _Maintain_ShakeHand_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "meta.proto",
}
