// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: ray.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DriverSubmitTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	FuncName      string                 `protobuf:"bytes,2,opt,name=func_name,json=funcName,proto3" json:"func_name,omitempty"`
	Args          [][]byte               `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	Dependencies  []string               `protobuf:"bytes,4,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverSubmitTaskRequest) Reset() {
	*x = DriverSubmitTaskRequest{}
	mi := &file_ray_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverSubmitTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverSubmitTaskRequest) ProtoMessage() {}

func (x *DriverSubmitTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ray_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverSubmitTaskRequest.ProtoReflect.Descriptor instead.
func (*DriverSubmitTaskRequest) Descriptor() ([]byte, []int) {
	return file_ray_proto_rawDescGZIP(), []int{0}
}

func (x *DriverSubmitTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *DriverSubmitTaskRequest) GetFuncName() string {
	if x != nil {
		return x.FuncName
	}
	return ""
}

func (x *DriverSubmitTaskRequest) GetArgs() [][]byte {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *DriverSubmitTaskRequest) GetDependencies() []string {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

type SchedulerSubmitTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchedulerSubmitTaskResponse) Reset() {
	*x = SchedulerSubmitTaskResponse{}
	mi := &file_ray_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchedulerSubmitTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchedulerSubmitTaskResponse) ProtoMessage() {}

func (x *SchedulerSubmitTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ray_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchedulerSubmitTaskResponse.ProtoReflect.Descriptor instead.
func (*SchedulerSubmitTaskResponse) Descriptor() ([]byte, []int) {
	return file_ray_proto_rawDescGZIP(), []int{1}
}

func (x *SchedulerSubmitTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SchedulerSubmitTaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

// 2. 调度器向 GCS 注册任务
type RegisterTaskToGCSRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Dependencies  []string               `protobuf:"bytes,3,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterTaskToGCSRequest) Reset() {
	*x = RegisterTaskToGCSRequest{}
	mi := &file_ray_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterTaskToGCSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterTaskToGCSRequest) ProtoMessage() {}

func (x *RegisterTaskToGCSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ray_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterTaskToGCSRequest.ProtoReflect.Descriptor instead.
func (*RegisterTaskToGCSRequest) Descriptor() ([]byte, []int) {
	return file_ray_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterTaskToGCSRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *RegisterTaskToGCSRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RegisterTaskToGCSRequest) GetDependencies() []string {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

type RegisterTaskToGCSResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterTaskToGCSResponse) Reset() {
	*x = RegisterTaskToGCSResponse{}
	mi := &file_ray_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterTaskToGCSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterTaskToGCSResponse) ProtoMessage() {}

func (x *RegisterTaskToGCSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ray_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterTaskToGCSResponse.ProtoReflect.Descriptor instead.
func (*RegisterTaskToGCSResponse) Descriptor() ([]byte, []int) {
	return file_ray_proto_rawDescGZIP(), []int{3}
}

// 3. Worker 向 Scheduler 拉取任务
type FetchTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchTaskRequest) Reset() {
	*x = FetchTaskRequest{}
	mi := &file_ray_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchTaskRequest) ProtoMessage() {}

func (x *FetchTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ray_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchTaskRequest.ProtoReflect.Descriptor instead.
func (*FetchTaskRequest) Descriptor() ([]byte, []int) {
	return file_ray_proto_rawDescGZIP(), []int{4}
}

func (x *FetchTaskRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

type FetchTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	FuncName      string                 `protobuf:"bytes,2,opt,name=func_name,json=funcName,proto3" json:"func_name,omitempty"`
	Args          [][]byte               `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	HasTask       bool                   `protobuf:"varint,4,opt,name=has_task,json=hasTask,proto3" json:"has_task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchTaskResponse) Reset() {
	*x = FetchTaskResponse{}
	mi := &file_ray_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchTaskResponse) ProtoMessage() {}

func (x *FetchTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ray_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchTaskResponse.ProtoReflect.Descriptor instead.
func (*FetchTaskResponse) Descriptor() ([]byte, []int) {
	return file_ray_proto_rawDescGZIP(), []int{5}
}

func (x *FetchTaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *FetchTaskResponse) GetFuncName() string {
	if x != nil {
		return x.FuncName
	}
	return ""
}

func (x *FetchTaskResponse) GetArgs() [][]byte {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *FetchTaskResponse) GetHasTask() bool {
	if x != nil {
		return x.HasTask
	}
	return false
}

// 4. Worker 向 GCS 查询对象位置
type GetObjectLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectId      string                 `protobuf:"bytes,1,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObjectLocationRequest) Reset() {
	*x = GetObjectLocationRequest{}
	mi := &file_ray_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectLocationRequest) ProtoMessage() {}

func (x *GetObjectLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ray_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectLocationRequest.ProtoReflect.Descriptor instead.
func (*GetObjectLocationRequest) Descriptor() ([]byte, []int) {
	return file_ray_proto_rawDescGZIP(), []int{6}
}

func (x *GetObjectLocationRequest) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

type GetObjectLocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeAddr      string                 `protobuf:"bytes,1,opt,name=node_addr,json=nodeAddr,proto3" json:"node_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObjectLocationResponse) Reset() {
	*x = GetObjectLocationResponse{}
	mi := &file_ray_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectLocationResponse) ProtoMessage() {}

func (x *GetObjectLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ray_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectLocationResponse.ProtoReflect.Descriptor instead.
func (*GetObjectLocationResponse) Descriptor() ([]byte, []int) {
	return file_ray_proto_rawDescGZIP(), []int{7}
}

func (x *GetObjectLocationResponse) GetNodeAddr() string {
	if x != nil {
		return x.NodeAddr
	}
	return ""
}

// 5. Worker 向 GCS 上报任务结果 & 对象
type ReportTaskResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	ObjectId      string                 `protobuf:"bytes,3,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	ResultData    []byte                 `protobuf:"bytes,4,opt,name=result_data,json=resultData,proto3" json:"result_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportTaskResultRequest) Reset() {
	*x = ReportTaskResultRequest{}
	mi := &file_ray_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTaskResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTaskResultRequest) ProtoMessage() {}

func (x *ReportTaskResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ray_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTaskResultRequest.ProtoReflect.Descriptor instead.
func (*ReportTaskResultRequest) Descriptor() ([]byte, []int) {
	return file_ray_proto_rawDescGZIP(), []int{8}
}

func (x *ReportTaskResultRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ReportTaskResultRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReportTaskResultRequest) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *ReportTaskResultRequest) GetResultData() []byte {
	if x != nil {
		return x.ResultData
	}
	return nil
}

type ReportTaskResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportTaskResultResponse) Reset() {
	*x = ReportTaskResultResponse{}
	mi := &file_ray_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTaskResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTaskResultResponse) ProtoMessage() {}

func (x *ReportTaskResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ray_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTaskResultResponse.ProtoReflect.Descriptor instead.
func (*ReportTaskResultResponse) Descriptor() ([]byte, []int) {
	return file_ray_proto_rawDescGZIP(), []int{9}
}

// 6. Driver 从 GCS 获取最终结果
type GetTaskResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResultRequest) Reset() {
	*x = GetTaskResultRequest{}
	mi := &file_ray_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResultRequest) ProtoMessage() {}

func (x *GetTaskResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ray_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResultRequest.ProtoReflect.Descriptor instead.
func (*GetTaskResultRequest) Descriptor() ([]byte, []int) {
	return file_ray_proto_rawDescGZIP(), []int{10}
}

func (x *GetTaskResultRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type GetTaskResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Result        []byte                 `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResultResponse) Reset() {
	*x = GetTaskResultResponse{}
	mi := &file_ray_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResultResponse) ProtoMessage() {}

func (x *GetTaskResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ray_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResultResponse.ProtoReflect.Descriptor instead.
func (*GetTaskResultResponse) Descriptor() ([]byte, []int) {
	return file_ray_proto_rawDescGZIP(), []int{11}
}

func (x *GetTaskResultResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetTaskResultResponse) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_ray_proto protoreflect.FileDescriptor

const file_ray_proto_rawDesc = "" +
	"\n" +
	"\tray.proto\x12\x06rayrpc\"\x87\x01\n" +
	"\x17DriverSubmitTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1b\n" +
	"\tfunc_name\x18\x02 \x01(\tR\bfuncName\x12\x12\n" +
	"\x04args\x18\x03 \x03(\fR\x04args\x12\"\n" +
	"\fdependencies\x18\x04 \x03(\tR\fdependencies\"P\n" +
	"\x1bSchedulerSubmitTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\"o\n" +
	"\x18RegisterTaskToGCSRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\"\n" +
	"\fdependencies\x18\x03 \x03(\tR\fdependencies\"\x1b\n" +
	"\x19RegisterTaskToGCSResponse\"/\n" +
	"\x10FetchTaskRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\"x\n" +
	"\x11FetchTaskResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1b\n" +
	"\tfunc_name\x18\x02 \x01(\tR\bfuncName\x12\x12\n" +
	"\x04args\x18\x03 \x03(\fR\x04args\x12\x19\n" +
	"\bhas_task\x18\x04 \x01(\bR\ahasTask\"7\n" +
	"\x18GetObjectLocationRequest\x12\x1b\n" +
	"\tobject_id\x18\x01 \x01(\tR\bobjectId\"8\n" +
	"\x19GetObjectLocationResponse\x12\x1b\n" +
	"\tnode_addr\x18\x01 \x01(\tR\bnodeAddr\"\x88\x01\n" +
	"\x17ReportTaskResultRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1b\n" +
	"\tobject_id\x18\x03 \x01(\tR\bobjectId\x12\x1f\n" +
	"\vresult_data\x18\x04 \x01(\fR\n" +
	"resultData\"\x1a\n" +
	"\x18ReportTaskResultResponse\"/\n" +
	"\x14GetTaskResultRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"G\n" +
	"\x15GetTaskResultResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x16\n" +
	"\x06result\x18\x02 \x01(\fR\x06resultB\x1eZ\x1cmini-ray/proto/rayrpc;rayrpcb\x06proto3"

var (
	file_ray_proto_rawDescOnce sync.Once
	file_ray_proto_rawDescData []byte
)

func file_ray_proto_rawDescGZIP() []byte {
	file_ray_proto_rawDescOnce.Do(func() {
		file_ray_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ray_proto_rawDesc), len(file_ray_proto_rawDesc)))
	})
	return file_ray_proto_rawDescData
}

var file_ray_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_ray_proto_goTypes = []any{
	(*DriverSubmitTaskRequest)(nil),     // 0: rayrpc.DriverSubmitTaskRequest
	(*SchedulerSubmitTaskResponse)(nil), // 1: rayrpc.SchedulerSubmitTaskResponse
	(*RegisterTaskToGCSRequest)(nil),    // 2: rayrpc.RegisterTaskToGCSRequest
	(*RegisterTaskToGCSResponse)(nil),   // 3: rayrpc.RegisterTaskToGCSResponse
	(*FetchTaskRequest)(nil),            // 4: rayrpc.FetchTaskRequest
	(*FetchTaskResponse)(nil),           // 5: rayrpc.FetchTaskResponse
	(*GetObjectLocationRequest)(nil),    // 6: rayrpc.GetObjectLocationRequest
	(*GetObjectLocationResponse)(nil),   // 7: rayrpc.GetObjectLocationResponse
	(*ReportTaskResultRequest)(nil),     // 8: rayrpc.ReportTaskResultRequest
	(*ReportTaskResultResponse)(nil),    // 9: rayrpc.ReportTaskResultResponse
	(*GetTaskResultRequest)(nil),        // 10: rayrpc.GetTaskResultRequest
	(*GetTaskResultResponse)(nil),       // 11: rayrpc.GetTaskResultResponse
}
var file_ray_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ray_proto_init() }
func file_ray_proto_init() {
	if File_ray_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ray_proto_rawDesc), len(file_ray_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ray_proto_goTypes,
		DependencyIndexes: file_ray_proto_depIdxs,
		MessageInfos:      file_ray_proto_msgTypes,
	}.Build()
	File_ray_proto = out.File
	file_ray_proto_goTypes = nil
	file_ray_proto_depIdxs = nil
}
